FROM mariadb:10.5.8


# Set environment variables for database access
ENV MYSQL_DATABASE=exampleDBrdrlf
ENV MYSQL_USER=exampleDBrdrlf
ENV MYSQL_PASSWORD=ZnT3yVQ0YS
ENV MYSQL_ROOT_PASSWORD=rockyLinux-123
